import type { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Contact from "../components/Contact";
import WorkExperience from "../components/WorkExperience";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import Link from "next/link";
import { Experience, PageInfo, Project, Skill, Social } from "../typings";
import { fetchPageInfo } from "../utils/fetchPageInfo";
import { fetchExperiences } from "../utils/fetchExperiences";
import { fetchSkills } from "../utils/fetchSkills";
import { fetchProjects } from "../utils/fetchProjects";
import { fetchSocials } from "../utils/fetchSocials";

type Props = {
  pageInfo: PageInfo;
  experiences: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
};

const Home = ({ pageInfo, experiences, skills, projects, socials }: Props) => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ab0a]/80 ">
      <Head>
        <title>Nauman's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>

      <Header socials={socials} />
      <section id="hero" className="snap-start">
        <Hero pageInfo={pageInfo} />
      </section>

      <section id="about" className="snap-center">
        <About pageInfo={pageInfo} />
      </section>
      {/* <section id="experience" className="snap-center">
        <WorkExperience experiences={experiences} />
      </section> */}
      <section id="skills" className="snap-start">
        <Skills skills={skills} />
      </section>
      <section id="projects" className="snap-start">
        <Projects projects={projects} />
      </section>
      <section id="contact" className="snap-start">
        <Contact />
      </section>

      <Link href="#hero">
        <footer className="sticky bottom-5 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <img
              // https://scontent.flko5-1.fna.fbcdn.net/v/t31.18172-8/258605_174345185960641_2216502_o.jpg?stp=c0.169.1536.1536a_dst-jpg_s851x315&_nc_cat=102&ccb=1-7&_nc_sid=da31f3&_nc_ohc=tsqrb6iZd2kAX9rxL7o&tn=r-gpQXaKy9bi75EC&_nc_ht=scontent.flko5-1.fna&oh=00_AfCxF8MfvFLqOBNwLo_zq8OabkpFSBkF454H5YcRKqJuJw&oe=63E2117E
              src="https://scontent.flko5-1.fna.fbcdn.net/v/t1.18169-9/188592_441378919257265_1742674667_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=174925&_nc_ohc=ITgZOowgClgAX-wMleA&_nc_ht=scontent.flko5-1.fna&oh=00_AfB3sVnxfKX6QrZbPfZpI0Cv_CZ_IOFExx4lLA72rgiDgQ&oe=63E2195F"
              alt=""
              className="h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer"
            />
          </div>
        </footer>
      </Link>
    </div>
  );
};

export default Home;

// per req -> then use getServerSideProps

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const experiences: Experience[] = await fetchExperiences();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();
  const socials: Social[] = await fetchSocials();

  return {
    props: {
      pageInfo,
      experiences,
      skills,
      projects,
      socials,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // At most once every 30 secs
    revalidate: 20,
  };
};
